/// <reference path="../../../typings/tsd.d.ts" />
var mainModule = angular.module('mainModule', []);
mainModule.controller("mainController", function ($scope) {
    $scope.myScopeVar = "the scope variable value";
}).directive("nghTemplateJs", function () {
    return {
        template: 'This is <strong>nghTemplateJs</strong> directive which generated by JavaScript Object, printing <em>{{myScopeVar}}</em>'
    };
}).directive("nghTemplateUrlDir", function () {
    return {
        templateUrl: 'nghTemplate.html'
    };
});
